apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xdnss.planum.mblb.net #has to be plural
  labels:
    planum.mblb.net/managed-by: "true"
spec:
  compositeTypeRef:
    apiVersion: planum.mblb.net/v1alpha1
    kind: XDns #has to be singular

  mode: Pipeline
  pipeline:
    - step: render-templates
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{- range $name := .observed.composite.resource.spec.parameters.dnsZoneNames }}
            ---
            apiVersion: network.azure.upbound.io/v1beta1
            kind: PrivateDNSZone
            metadata:
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: {{ $name }}
                crossplane.io/external-name: {{ $name }}
              name: {{ $name | replace "." "-"}}
            spec:
              forProvider:
                resourceGroupName: {{ $.observed.composite.resource.spec.parameters.resourceGroupName }}
              providerConfigRef:
                  name: {{ $.observed.composite.resource.spec.resourceConfig.providerConfigName }}
            ---
            apiVersion: network.azure.upbound.io/v1beta1
            kind: PrivateDNSZoneVirtualNetworkLink
            metadata:
              name: tohub
            spec:
              forProvider:
                privateDnsZoneName: {{ $name }}
                resourceGroupName: {{ $.observed.composite.resource.spec.parameters.resourceGroupName }}
                virtualNetworkId: "/subscriptions/af8f4f3a-6537-4f0f-8960-8a60d32ff35b/resourceGroups/rg-hub1-8glk9-tst-westeurope/providers/Microsoft.Network/virtualNetworks/vnet-hub1-8glk9-tst-westeurope"
            ---
            apiVersion: planum.mblb.net/v1alpha1
            kind: XDns
            {{ if eq $.observed.resources nil }}
            status:
              outputs: {}
            {{ else }}
            status:
              outputs:
                {{ $name | lower }}: {{ (index $.observed.resources $name).resource.status.atProvider.id }}
            {{ end }}
            {{- end }}

    - step: auto-ready
      functionRef:
        name: function-auto-ready
