apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xdnss.planum.mblb.net #has to be plural
  labels:
    planum.mblb.net/managed-by: "true"
spec:
  compositeTypeRef:
    apiVersion: planum.mblb.net/v1alpha1
    kind: XDns #has to be singular

  mode: Pipeline
  pipeline:

    - step: patch-and-transform
      functionRef:
        name: upbound-function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        
        resources:
        - name: environment-config
          readinessChecks:
          - type: None
          base:
            apiVersion: apiextensions.crossplane.io/v1alpha1
            kind: EnvironmentConfig
            metadata:
              labels:
                type: xdns
                name: 
              name: 
            data:
          patches:
            - type: CombineFromComposite
              combine:
                variables:
                  - fromFieldPath: metadata.name
                  - fromFieldPath: spec.resourceConfig.environment
                  - fromFieldPath: spec.resourceConfig.location
                strategy: string
                string:
                  fmt: "ec-%s-%s-%s"
              toFieldPath: metadata.name
            - type: FromCompositeFieldPath
              fromFieldPath: metadata.name
              toFieldPath: metadata.labels.name
            - type: FromCompositeFieldPath
              fromFieldPath: status.outputs
              toFieldPath: data.outputs

    - step: render-templates
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{ $prefix := printf "%s-%s-%s" $.observed.composite.resource.metadata.name $.observed.composite.resource.spec.resourceConfig.environment $.observed.composite.resource.spec.resourceConfig.location  }}
            ---
            apiVersion: network.azure.upbound.io/v1beta1
            kind: PrivateDNSResolver
            metadata:
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: dnspr-{{ $prefix }}
                gotemplating.fn.crossplane.io/ready: "True"
              name: dnspr-{{ $prefix }}
            spec:
              forProvider:
                location: {{ $.observed.composite.resource.spec.resourceConfig.location }}
                resourceGroupName: {{ $.observed.composite.resource.spec.parameters.resourceGroupName }}
                virtualNetworkId: {{ $.observed.composite.resource.spec.parameters.hubVirtualNetworkId }}
              providerConfigRef:
                name: {{ $.observed.composite.resource.spec.resourceConfig.providerConfigName }}
            ---
            apiVersion: planum.mblb.net/v1alpha1
            kind: InboundEndpoint
            metadata:
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: in-{{ $prefix }}
                gotemplating.fn.crossplane.io/ready: "True"
              name: in-{{ $prefix }}
            spec:
              resourceGroupName: {{ $.observed.composite.resource.spec.parameters.resourceGroupName }}
              location: {{ $.observed.composite.resource.spec.resourceConfig.location }}
              privateDnsResolverName: {{ printf "dnspr-%s" $prefix }}
              subnetId: {{ $.observed.composite.resource.spec.parameters.dnsSubnetId }}
              providerConfigName: {{ $.observed.composite.resource.spec.resourceConfig.providerConfigName }}
            ---
            {{- range $name := .observed.composite.resource.spec.parameters.dnsZoneNames }}
            ---
            apiVersion: network.azure.upbound.io/v1beta1
            kind: PrivateDNSZone
            metadata:
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: {{ $name }}
                gotemplating.fn.crossplane.io/ready: "True"
                crossplane.io/external-name: {{ $name }}
              name: {{ $name | replace "." "-"}}
            spec:
              forProvider:
                resourceGroupName: {{ $.observed.composite.resource.spec.parameters.resourceGroupName }}
              providerConfigRef:
                  name: {{ $.observed.composite.resource.spec.resourceConfig.providerConfigName }}
            ---
            apiVersion: network.azure.upbound.io/v1beta1
            kind: PrivateDNSZoneVirtualNetworkLink
            metadata:
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: {{ $name }}-link
                gotemplating.fn.crossplane.io/ready: "True"
                crossplane.io/external-name: {{ $name }}-link
              name: to-hub-{{ $name | replace "." "-"}}
            spec:
              forProvider:
                privateDnsZoneName: {{ $name }}
                resourceGroupName: {{ $.observed.composite.resource.spec.parameters.resourceGroupName }}
                virtualNetworkId: {{ $.observed.composite.resource.spec.parameters.hubVirtualNetworkId }}
              providerConfigRef:
                name: {{ $.observed.composite.resource.spec.resourceConfig.providerConfigName }}
            ---
            apiVersion: planum.mblb.net/v1alpha1
            kind: XDns
            {{ if eq $.observed.resources nil }}
            status:
              outputs: {}
            {{ else }}
            status:
              outputs:
                {{ $name | lower }}: {{ (index $.observed.resources $name).resource.status.atProvider.id }}
                privateDnsResolverInboundEndpointIp: {{ (index $.observed.resources (printf "in-%s" $prefix)).resource.status.atProvider.inboundEndpointIp }}
            {{ end }}
            {{- end }}

    - step: auto-ready
      functionRef:
        name: function-auto-ready
