apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xdnss.planum.mblb.net
spec:
  group: planum.mblb.net
  names:
    kind: XDns
    plural: xdnss

  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              resourceConfig:
                description: ResourceConfig defines general properties
                type: object
                properties:
                  providerConfigName:
                    type: string
                  location:
                    type: string
                  environment:
                    type: string  
                required:
                  - providerConfigName
                  - location
              parameters:
                description: DNS Input parameters
                type: object
                properties:
                  resourceGroupName:
                    type: string
                  dnsZoneNames:
                    items:
                      type: string
                    type: array
                  hubVirtualNetworkId:
                    type: string
                    default: ""
                  dnsSubnetId:
                    type: string
                    default: ""
                required:
                  - dnsZoneNames
          status:
            type: object
            properties:
              outputs:
                type: object
                additionalProperties:
                  type: string