apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xhubandspokes.planum.mblb.net
spec:
  group: planum.mblb.net
  names:
    kind: XHubAndSpoke
    plural: xhubandspokes

  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              resourceConfig:
                description: ResourceConfig defines general properties
                type: object
                properties:
                  location:
                    type: string
                  environment:
                    type: string
                  spokeName:
                    type: string
                  tenantId:
                    type: string
                required:
                  - location
              parameters:
                description: Spoke Input parameters
                type: object
                properties:
                  hubConfig:
                    description: hubConfig defines configuration of the Hub
                    type: object
                    properties:
                      providerConfigName:
                        type: string
                      vnetAddressPrefix:
                        type: string
                      vnetGatewayConfig:
                        type: object
                        default:
                          addressSpace:
                          - "192.168.100.0/24"
                        properties:
                          sku:
                            type: string
                            default: VpnGw1
                          addressSpace:
                            items:
                              type: string
                            type: array
                          vpnClientProtocols:
                            enum:
                            - SSTP
                            - IkeV2
                            - OpenVPN
                            type: string
                            default: OpenVPN
                          vpnAuthTypes:
                            enum:
                            - AAD
                            - Radius
                            - Certificate
                            type: string
                            default: AAD
                      lgwGatewayConfig:
                        type: object
                        default: 
                          gatewayAddress: "10.10.10.10"
                          addressSpace:
                          - "10.10.10.0/24"
                          connectionName: "mobilab"
                          sharedKeySecretKeyName: "lgwSharedKey" ## Should match the key in secrets.yaml
                        properties:
                          addressSpace:
                            items:
                              type: string
                            type: array
                          gatewayAddress:
                            type: string
                          connectionName:
                            type: string
                          sharedKeySecretKeyName:
                            type: string
                      dnsZoneNames:
                        items:
                          type: string
                        type: array
                        default:
                        - "privatelink.azuredatabricks.net"
                        - "privatelink.blob.core.windows.net"
                        - "privatelink.datafactory.azure.net"
                        - "privatelink.dfs.core.windows.net"
                        - "privatelink.file.core.windows.net"
                        - "privatelink.vaultcore.azure.net"
                        - "privatelink.servicebus.windows.net"

                  spokeConfigs:
                    description: spokeConfigs defines configuration of the all the spokes
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        providerConfigName:
                          type: string
                        vnetAddressSpace:
                          type: array
                          items:
                            type: string
                        subnets:
                          type: array
                          default: []
                          items:
                            type: object
                            properties:
                              name:
                                type: string
                              addressSpace:
                                type: string
          status:
            type: object
            properties:
              outputs:
                type: object
                additionalProperties:
                  type: string
