apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: firewallrules.planum.mblb.net
spec:
  group: planum.mblb.net
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                providerConfigName:
                  type: string
                action:
                  type: string
                  enum:
                  - "Allow"
                  - "Deny"
                firewallName:
                  type: string
                resourceGroupName:
                  type: string
                action:
                  type: string
                  enum:
                  - Allow
                  - Deny
                priority:
                  type: integer
                  minimum: 100
                  maximum: 65000
                rules:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      protocols:
                        type: string
                        enum:
                        - "Any"
                        - "ICMP"
                        - "TCP"
                        - "UDP"
                      destinationAddress:
                        type: array
                        items:
                          type: string
                      destinationPorts:
                        type: array
                        items:
                          type: string
                      sourceAddress:
                        type: array
                        items:
                          type: string
              required:
              - providerConfigName

            status:
            type: object
            properties:
              conditions:
                description: Conditions of the resource.
                items:
                  description: A Condition that may apply to a resource.
                  properties:
                    lastTransitionTime:
                      description: LastTransitionTime is the last time this condition
                        transitioned from one status to another.
                      format: date-time
                      type: string
                    message:
                      description: A Message containing details about this condition's
                        last transition from one status to another, if any.
                      type: string
                    reason:
                      description: A Reason for this condition's last transition from
                        one status to another.
                      type: string
                    status:
                      description: Status of this condition; is it currently True,
                        False, or Unknown?
                      type: string
                    type:
                      description: Type of this condition. At most one of each condition
                        type may apply to a resource at any point in time.
                      type: string
                  required:
                  - lastTransitionTime
                  - reason
                  - status
                  - type
                  type: object
                type: array
                x-kubernetes-list-map-keys:
                - type
                x-kubernetes-list-type: map
              atProvider:
                type: object
                properties:
                  inboundEndpointIp: 
                    type: string
                    default: "novalue"
  names:
    kind: FirewallRule
    plural: firewallrules
  scope: Cluster