apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: foos.planum.mblb.net
spec:
  group: planum.mblb.net
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                bar:
                  type: string
              required:
                - bar
            status:
              type: object
              properties:
                outputs:
                  type: object
                  additionalProperties:
                    type: string
  names:
    kind: Foo
    plural: foos
  scope: Cluster