apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: githubrepos.planum.mblb.net
spec:
  group: planum.mblb.net
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
              required:
                - name
  names:
    kind: GitHubRepo
    plural: githubrepos
  scope: Cluster