apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: hubs.isaac.mblb.net
spec:
  group: isaac.mblb.net
  names:
    kind: Hub
    plural: hubs
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                providerConfigName:
                  type: string
                addressSpace:
                  type: array
                  items:
                    type: string
                tags:
                  type: object
                  additionalProperties:
                    type: string
              required:
                - providerConfigName
                - addressSpace
      served: true
      referenceable: true
  claimNames:
    kind: HubClaim
    plural: hubclaims