apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xhubs.planum.mblb.net
spec:
  group: planum.mblb.net
  names:
    kind: XHub
    plural: xhubs
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                providerConfigName:
                  type: string
                addressSpace:
                  type: array
                  items:
                    type: string
                firewallSubnetAddressSpace:
                  type: string
                gatewaySubnetAddressSpace:
                  type: string
                tags:
                  type: object
                  additionalProperties:
                    type: string
              required:
                - providerConfigName
                - addressSpace
                - firewallSubnetAddressSpace
                - gatewaySubnetAddressSpace
      served: true
      referenceable: true
  claimNames:
    kind: Hub
    plural: hubs