apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: inboundendpoints.planum.mblb.net
spec:
  group: planum.mblb.net
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                resourceGroupName:
                  type: string
                location:
                  type: string
                privateDnsResolverName:
                  type: string
                subnetId:
                  type: string

              required:
                - privateDnsResolverName
                - subnetId
                - resourceGroupName
                - location

            status:
              type: object
              properties:
                conditions:
                  description: Conditions of the resource.
                  items:
                    description: A Condition that may apply to a resource.
                    properties:
                      lastTransitionTime:
                        description: LastTransitionTime is the last time this condition
                          transitioned from one status to another.
                        format: date-time
                        type: string
                      message:
                        description: A Message containing details about this condition's
                          last transition from one status to another, if any.
                        type: string
                      reason:
                        description: A Reason for this condition's last transition from
                          one status to another.
                        type: string
                      status:
                        description: Status of this condition; is it currently True,
                          False, or Unknown?
                        type: string
                      type:
                        description: Type of this condition. At most one of each condition
                          type may apply to a resource at any point in time.
                        type: string
                    required:
                    - lastTransitionTime
                    - reason
                    - status
                    - type
                    type: object
                  type: array
                  x-kubernetes-list-map-keys:
                  - type
                  x-kubernetes-list-type: map
                atProvider:
                  type: object
                  properties:
                    inboundEndpointIp: 
                      type: string
                      default: "novalue"

  names:
    kind: InboundEndpoint
    plural: inboundendpoints
  scope: Cluster