apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vmids.planum.mblb.net
spec:
  group: planum.mblb.net
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                identity:
                  type: string
                vmResourceGroup:
                  type: string
                vmName:
                  type: string
              required:
                - identity
                - vmResourceGroup
                - vmName
  names:
    kind: VmId
    plural: vmids
  scope: Cluster