apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vmssids.planum.mblb.net
spec:
  group: planum.mblb.net
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                identity:
                  type: string
              required:
                - identity
  names:
    kind: VmssId
    plural: vmssids
  scope: Cluster