apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xscopes.planum.mblb.net
spec:
  group: planum.mblb.net
  names:
    kind: XScope
    plural: xscopes
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                location:
                  type: string
                  default: "westeurope"
                subscriptionId:
                  type: string
                repo:
                  type: string
                providerConfigName:
                  type: string
              required:
                - subscriptionId
                - repo
                - providerConfigName
            status:
              type: object
              properties:
                outputs:
                  type: object
                  additionalProperties:
                    type: string
      served: true
      referenceable: true
  claimNames:
    kind: Scope
    plural: scopes