apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xscopeidentities.planum.mblb.net
spec:
  group: planum.mblb.net
  names:
    kind: XScopeIdentity
    plural: xscopeidentities
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                identity:
                  type: string
              required:
                - identity
      served: true
      referenceable: true
  claimNames:
    kind: ScopeIdentity
    plural: scopeidentities