apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xspokes.planum.mblb.net
spec:
  group: planum.mblb.net
  names:
    kind: XSpoke
    plural: xspokes
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                providerConfigRef:
                  type: string
                location:
                  type: string
                tags:
                  type: object
                  additionalProperties:
                    type: string
                addressSpace:
                  type: array
                  items:
                    type: string
                subnets:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      addressRange:
                        type: string
                hubVirtualNetworkId:
                  type: string
                hubResourceGroupName:
                  type: string
                hubVirtualNetworkName:
                  type: string
                hubProviderConfigRef:
                  type: string
              required:
                - providerConfigRef
                - location
                - addressSpace
                - hubVirtualNetworkId
                - hubResourceGroupName
                - hubVirtualNetworkName
                - hubProviderConfigRef
      served: true
      referenceable: true
  claimNames:
    kind: Spoke
    plural: spokes