apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xhubs.planum.mblb.net
spec:
  group: planum.mblb.net
  names:
    kind: XHub
    plural: xhubs

  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              resourceConfig:
                description: ResourceConfig defines general properties
                type: object
                properties:
                  providerConfigName:
                    type: string
                  location:
                    type: string
                  environment:
                    type: string  
                  tenantId:
                    type: string 
                  subscriptionId:
                    type: string
                required:
                  - providerConfigName
                  - location
              parameters:
                description: Hub Input parameters
                type: object
                properties:
                  vnetAddressSpace:
                    type: array
                    items:
                      type: string
                  spokeAddressSpace:
                    type: array
                    items:
                      type: string
                  subnets:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        addressSpace:
                          type: string
                  vnetGatewayConfig:
                    type: object
                    properties:
                      sku:
                        type: string
                        default: VpnGw1
                      addressSpace:
                        items:
                          type: string
                        type: array
                      vpnClientProtocols:
                        enum:
                        - SSTP
                        - IkeV2
                        - OpenVPN
                        type: string
                        default: OpenVPN
                      vpnAuthTypes:
                        enum:
                        - AAD
                        - Radius
                        - Certificate
                        type: string
                        default: AAD
                  lgwGatewayConfig:
                    type: object
                    properties:
                      addressSpace:
                        items:
                          type: string
                        type: array
                      gatewayAddress:
                        type: string
                      connectionName:
                        type: string
                      sharedKeySecretKeyName:
                        type: string
                  dnsZoneNames:
                    items:
                      type: string
                    type: array
          status:
            type: object
            properties:
              outputs:
                type: object
                additionalProperties:
                  type: string