apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: hub
spec:
  compositeTypeRef:
    apiVersion: planum.mblb.net/v1alpha1
    kind: XHub
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: rg
            base:
              apiVersion: azure.upbound.io/v1beta1
              kind: ResourceGroup
              spec:
                forProvider:
                  location: West Europe
                providerConfigRef:
                  name: X
            patches:
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: metadata.name
                  strategy: string
                  string:
                    fmt: "rg-hub-%s"
                toFieldPath: metadata.name
              - type: FromCompositeFieldPath
                fromFieldPath: spec.providerConfigName
                toFieldPath: spec.providerConfigRef.name
              - type: FromCompositeFieldPath
                fromFieldPath: spec.tags
                toFieldPath: spec.forProvider.tags
          - name: vnet
            base:
              apiVersion: network.azure.upbound.io/v1beta1
              kind: VirtualNetwork
              spec:
                forProvider:
                  addressSpace:
                    - 10.0.0.0/16
                  location: "West Europe"
                  resourceGroupNameSelector:
                    matchControllerRef: true
                providerConfigRef:
                  name: X
            patches:
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: metadata.name
                  strategy: string
                  string:
                    fmt: "vnet-hub-%s"
                toFieldPath: metadata.name
              - type: FromCompositeFieldPath
                fromFieldPath: spec.addressSpace
                toFieldPath: spec.forProvider.addressSpace
              - type: FromCompositeFieldPath
                fromFieldPath: spec.providerConfigName
                toFieldPath: spec.providerConfigRef.name
          - name: firewallSubnet
            base:
              apiVersion: network.azure.upbound.io/v1beta1
              kind: Subnet
              spec:
                forProvider:
                  addressPrefixes:
                    - 10.0.0.0/24
                  resourceGroupNameSelector:
                    matchControllerRef: true
                  virtualNetworkNameSelector:
                    matchControllerRef: true
            patches:
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: metadata.name
                  strategy: string
                  string:
                    fmt: "snet-hubfw-%s"
                toFieldPath: metadata.name
              - type: FromCompositeFieldPath
                fromFieldPath: spec.firewallSubnetAddressSpace
                toFieldPath: spec.forProvider.addressPrefixes[0]
          - name: gatewaySubnet
            base:
              apiVersion: network.azure.upbound.io/v1beta1
              kind: Subnet
              metadata:
                annotations:
                  crossplane.io/external-name: GatewaySubnet
              spec:
                forProvider:
                  addressPrefixes:
                    - 10.0.1.0/24
                  resourceGroupNameSelector:
                    matchControllerRef: true
                  virtualNetworkNameSelector:
                    matchControllerRef: true
            patches:
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: metadata.name
                  strategy: string
                  string:
                    fmt: "snet-hubgw-%s"
                toFieldPath: metadata.name
              - type: FromCompositeFieldPath
                fromFieldPath: spec.gatewaySubnetAddressSpace
                toFieldPath: spec.forProvider.addressPrefixes[0]
