apiVersion: v1
kind: ConfigMap
metadata:
  name: azcli
  namespace: default
data:
  crds.json: |
    {
      "crds": [
        {
          "api-resource": "vmssids.v1alpha1.planum.mblb.net",
          "create-script": "vmssids-create.sh",
          "delete-script": "vmssids-delete.sh"
        },
        {
          "api-resource": "foos.v1alpha1.planum.mblb.net",
          "create-script": "foos-create.sh",
          "delete-script": "foos-delete.sh"
        }
      ]      
    }
  "vmssids-create.sh": |
    echo "vmssid create $1"
    echo $1 | jq -r '.spec.identity'
    az vmss identity assign -g mrg-planum1-aks-rg -n aks-agentpool-16645957-vmss --identities $(echo $1 | jq -r '.spec.identity')
  "vmssids-delete.sh": |
    echo "vmssid delete $1"
  "foos-create.sh": |
    echo "foo create $1"
  "foos-delete.sh": |
    echo "foo delete $1"
