apiVersion: v1
kind: ConfigMap
metadata:
  name: azcli
  namespace: planum
data:
  run.sh: |
    wget "https://dl.k8s.io/release/$(wget -O - https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    principalId=$(kubectl get configmap vm -n planum -ojson | jq -r '.data.vmIdentityPrincipalId')
    az login --identity --username $principalId
    apk add github-cli
    while true
    do
      crds=$(cat /etc/config/crds.json | jq -c '.crds[]')
      for crd in $crds; 
      do 
        crs=$(kubectl get $(echo $crd | jq -r '."api-resource"') -o json | jq -c '.items[]');
        crs_create=$(echo $crs|jq -c 'select( .metadata.deletionTimestamp == null)')
        for cr in $crs_create; 
        do
          bash $(echo $crd | jq -r '."create-script"' | sed 's/^/\/etc\/config\//') $cr; 
        done; 
        crs_delete=$(echo $crs|jq -c 'select( .metadata.deletionTimestamp != null)')
        for cr in $crs_delete; 
        do
          echo $crd | jq -r '."delete-script"' | sed 's/^/\/etc\/config\//'
          bash $(echo $crd | jq -r '."delete-script"' | sed 's/^/\/etc\/config\//') $cr; 
        done; 
      done
      echo "sleep 60s..."
      sleep 60
    done
  crds.json: |
    {
      "crds": [
        {
          "api-resource": "githubrepos.v1alpha1.planum.mblb.net",
          "create-script": "githubrepos-create.sh",
          "delete-script": "githubrepos-delete.sh"
        },
        {
          "api-resource": "vmids.v1alpha1.planum.mblb.net",
          "create-script": "vmids-create.sh",
          "delete-script": "vmids-delete.sh"
        },
        {
          "api-resource": "vmssids.v1alpha1.planum.mblb.net",
          "create-script": "vmssids-create.sh",
          "delete-script": "vmssids-delete.sh"
        },
        {
          "api-resource": "foos.v1alpha1.planum.mblb.net",
          "create-script": "foos-create.sh",
          "delete-script": "foos-delete.sh"
        }
      ]      
    }
  "githubrepos-create.sh": |
    echo "githubrepo create $1"
    gitHubSecret=$(kubectl get secret github -n planum -ojson)
    gitHubOrganization=$(echo $gitHubSecret | jq '.data.gitHubOrganization' | base64 -d)
    gitHubToken=$(echo $gitHubSecret | jq '.data.gitHubToken' | base64 -d)
    echo $gitHubToken | gh auth login -h github.com -p https --with-token
    name=$(echo $1 | jq -r '.spec.name')
    id=$(gh api --method GET -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "/repos/$gitHubOrganization/$name" | jq '.id')
    if test -z "$id"
    then
      echo "creating $name repo..." 
    else
      echo "$name repo already exists" 
    fi
  "githubrepos-delete.sh": |
    echo "githubrepo delete $1"
  "vmids-create.sh": |
    echo "vmid create $1"
    id=$(echo $1 | jq -r '.spec.identity')
    VM_RG=$(echo $1 | jq -r '.spec.vmResourceGroup')
    VM_NAME=$(echo $1 | jq -r '.spec.vmName')
    existing=$(az vm identity show -g $VM_RG -n $VM_NAME | grep "$id\":")
    if test -z "$existing"
    then
      az vm identity assign -g $VM_RG -n $VM_NAME --identities $id
      echo $1 | jq '.metadata += {finalizers: ["finalizer.planum.mblb.net"]}' | kubectl apply -f -
    else
      echo "$id is already assigned to $VM_NAME" 
    fi
  "vmids-delete.sh": |
    echo "vmid delete $1"
    id=$(echo $1 | jq -r '.spec.identity')
    VM_RG=$(echo $1 | jq -r '.spec.vmResourceGroup')
    VM_NAME=$(echo $1 | jq -r '.spec.vmName')
    existing=$(az vm identity show -g $VM_RG -n $VM_NAME | grep "$id\":")
    if test -z "$existing"
    then
      echo "$id is not assigned to $VM_NAME" 
    else
      az vm identity remove -g $VM_RG -n $VM_NAME --identities $id
    fi
    echo $1 | jq -c 'del(.metadata.finalizers[])' | kubectl apply -f -
  "vmssids-create.sh": |
    echo "vmssid create $1"
    id=$(echo $1 | jq -r '.spec.identity')
    VMSS_RG=$(echo $1 | jq -r '.spec.vmssResourceGroup')
    VMSS_NAME=$(echo $1 | jq -r '.spec.vmssName')
    existing=$(az vmss identity show -g $VMSS_RG -n $VMSS_NAME | grep subscriptions | sed 's/\"//g; s/://g; s/{//g' | awk '{$1=$1};1')
    if [[ "$existing" == *"$id"*  ]]
    then
      echo "$id is already assigned to $VMSS_NAME" 
    else
      az vmss identity assign -g $VMSS_RG -n $VMSS_NAME --identities $id
      echo $1 | jq '.metadata += {finalizers: ["finalizer.planum.mblb.net"]}' | kubectl apply -f -
    fi
  "vmssids-delete.sh": |
    echo "vmssid delete $1"
    id=$(echo $1 | jq -r '.spec.identity')
    VMSS_RG=$(echo $1 | jq -r '.spec.vmssResourceGroup')
    VMSS_NAME=$(echo $1 | jq -r '.spec.vmssName')
    existing=$(az vmss identity show -g $VMSS_RG -n $VMSS_NAME | grep subscriptions | sed 's/\"//g; s/://g; s/{//g' | awk '{$1=$1};1')
    if [[ "$existing" == *"$id"*  ]]
    then
      az vmss identity remove -g $VMSS_RG -n $VMSS_NAME --identities $id
    else
      echo "$id is not assigned to $VMSS_NAME" 
    fi
    echo $1 | jq -c 'del(.metadata.finalizers[])' | kubectl apply -f -
  "foos-create.sh": |
    echo "foo create $1"
  "foos-delete.sh": |
    echo "foo delete $1"
