apiVersion: v1
kind: ConfigMap
metadata:
  name: azcli
  namespace: default
data:
  crds.json: |
    {
      "crds": [
        {
          "api-resource": "vmssids.v1alpha1.planum.mblb.net",
          "create-script": "vmssids-create.sh",
          "delete-script": "vmssids-delete.sh"
        },
        {
          "api-resource": "foos.v1alpha1.planum.mblb.net",
          "create-script": "foos-create.sh",
          "delete-script": "foos-delete.sh"
        }
      ]      
    }
  "vmssids-create.sh": |
    echo "vmssid create"
  "vmssids-delete.sh": |
    echo "vmssid delete"
  "foos-create.sh": |
    echo "foo create"
  "foos-delete.sh": |
    echo "foo delete"
