apiVersion: v1
kind: Pod
metadata:
  name: azcli
  namespace: default
spec:
  containers:
    - image: mcr.microsoft.com/azure-cli
      command:
        - "bash"
        - "-c"
        - "tail -f /dev/null"
      imagePullPolicy: IfNotPresent
      name: azcli
  restartPolicy: Always