apiVersion: v1
kind: Pod
metadata:
  name: azcli
  namespace: planum
spec:
  containers:
    - image: mcr.microsoft.com/azure-cli
      command:
        - "bash"
        - "/etc/config/run.sh"
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      imagePullPolicy: IfNotPresent
      name: azcli
  restartPolicy: Always
  volumes:
    - name: config-volume
      configMap:
        name: azcli
