apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xdmlzs.planum.mblb.net #has to be plural
  labels:
    planum.mblb.net/managed-by: "true"
spec:
  environment:
    environmentConfigs:
      - type: Selector
        selector:
          matchLabels:
            - key: type
              type: Value
              value: xnetwork
            - key: name
              type: FromCompositeFieldPath
              valueFromFieldPath: spec.xNetworkName

      - type: Selector
        selector:
          matchLabels:
            - key: type
              type: Value
              value: xdns
            - key: name
              type: FromCompositeFieldPath
              valueFromFieldPath: spec.xDnsName

  compositeTypeRef:
    apiVersion: planum.mblb.net/v1alpha1
    kind: XDmlz #has to be singular

  mode: Pipeline
  pipeline:
    - step: render-dmlz-objects
      functionRef:
        name: upbound-function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources

        resources:
        - name: snet-dmlz-pe
          base:
            apiVersion: network.azure.upbound.io/v1beta1
            kind: Subnet
            metadata:
              name: snet-dmlz-pe
              labels:
                planum.mblb.net/component: snet-dmlz-pe
            spec:
              forProvider:
                addressPrefixes:
                virtualNetworkName:
                resourceGroupName:
          patches:
          - type: FromCompositeFieldPath
            fromFieldPath: spec.providerConfigName
            toFieldPath: spec.providerConfigRef.name
          - type: FromEnvironmentFieldPath
            fromFieldPath: outputs.ResourceGroupName
            toFieldPath: spec.forProvider.resourceGroupName
          - type: FromEnvironmentFieldPath
            fromFieldPath: outputs.VirtualNetworkName
            toFieldPath: spec.forProvider.virtualNetworkName
          - type: FromEnvironmentFieldPath
            fromFieldPath: outputs.vnetAddressPrefix
            toFieldPath: spec.forProvider.addressPrefixes[0]
            transforms:
            - type: string
              string:
                type: Format
                fmt: "%s.96/27"

        - name: snet-dmlz-dbw-public
          base:
            apiVersion: network.azure.upbound.io/v1beta1
            kind: Subnet
            metadata:
              name: snet-dmlz-dbw-public
              labels:
                planum.mblb.net/component: snet-dmlz-dbw-public
            spec:
              forProvider:
                addressPrefixes:
                virtualNetworkName:
                resourceGroupName:
                delegation:
                - name: "subnet-delegation"
                  serviceDelegation:
                  - name: "Microsoft.Databricks/workspaces"
                    actions: 
                    - "Microsoft.Network/virtualNetworks/subnets/join/action"
                    - "Microsoft.Network/virtualNetworks/subnets/prepareNetworkPolicies/action"
                    - "Microsoft.Network/virtualNetworks/subnets/unprepareNetworkPolicies/action"
          patches:
          - type: FromCompositeFieldPath
            fromFieldPath: spec.providerConfigName
            toFieldPath: spec.providerConfigRef.name
          - type: FromEnvironmentFieldPath
            fromFieldPath: outputs.ResourceGroupName
            toFieldPath: spec.forProvider.resourceGroupName
          - type: FromEnvironmentFieldPath
            fromFieldPath: outputs.VirtualNetworkName
            toFieldPath: spec.forProvider.virtualNetworkName
          - type: FromEnvironmentFieldPath
            fromFieldPath: outputs.vnetAddressPrefix
            toFieldPath: spec.forProvider.addressPrefixes[0]
            transforms:
            - type: string
              string:
                type: Format
                fmt: "%s.128/26"
          - type: ToCompositeFieldPath
            fromFieldPath: status.atProvider.id
            toFieldPath: status.outputs.dbwPublicSubnetId

        - name: snet-dmlz-dbw-private
          base:
            apiVersion: network.azure.upbound.io/v1beta1
            kind: Subnet
            metadata:
              name: snet-dmlz-dbw-private
              labels:
                planum.mblb.net/component: snet-dmlz-dbw-private
            spec:
              forProvider:
                addressPrefixes:
                virtualNetworkName:
                resourceGroupName:
                delegation:
                - name: "subnet-delegation"
                  serviceDelegation:
                  - name: "Microsoft.Databricks/workspaces"
                    actions: 
                    - "Microsoft.Network/virtualNetworks/subnets/join/action"
                    - "Microsoft.Network/virtualNetworks/subnets/prepareNetworkPolicies/action"
                    - "Microsoft.Network/virtualNetworks/subnets/unprepareNetworkPolicies/action"
          patches:
          - type: FromCompositeFieldPath
            fromFieldPath: spec.providerConfigName
            toFieldPath: spec.providerConfigRef.name
          - type: FromEnvironmentFieldPath
            fromFieldPath: outputs.ResourceGroupName
            toFieldPath: spec.forProvider.resourceGroupName
          - type: FromEnvironmentFieldPath
            fromFieldPath: outputs.VirtualNetworkName
            toFieldPath: spec.forProvider.virtualNetworkName
          - type: FromEnvironmentFieldPath
            fromFieldPath: outputs.vnetAddressPrefix
            toFieldPath: spec.forProvider.addressPrefixes[0]
            transforms:
            - type: string
              string:
                type: Format
                fmt: "%s.192/26"
          - type: ToCompositeFieldPath
            fromFieldPath: status.atProvider.id
            toFieldPath: status.outputs.dbwPrivateSubnetId
              
        - name: snet-dmlz-agent
          readinessChecks:
          - type: None
          base:
            apiVersion: network.azure.upbound.io/v1beta1
            kind: Subnet
            metadata:
              name: snet-dmlz-agent
              labels:
                planum.mblb.net/component: snet-dmlz-agent
            spec:
              forProvider:
                addressPrefixes:
                virtualNetworkName:
                resourceGroupName:
          patches:
          - type: FromCompositeFieldPath
            fromFieldPath: spec.providerConfigName
            toFieldPath: spec.providerConfigRef.name
          - type: FromEnvironmentFieldPath
            fromFieldPath: outputs.ResourceGroupName
            toFieldPath: spec.forProvider.resourceGroupName
          - type: FromEnvironmentFieldPath
            fromFieldPath: outputs.VirtualNetworkName
            toFieldPath: spec.forProvider.virtualNetworkName
          - type: FromEnvironmentFieldPath
            fromFieldPath: outputs.vnetAddressPrefix
            toFieldPath: spec.forProvider.addressPrefixes[0]
            transforms:
            - type: string
              string:
                type: Format
                fmt: "%s.80/29"

        - name: dbw-dmlz-nsg
          base:
            apiVersion: planum.mblb.net/v1alpha1
            kind: XDbwNsg
            metadata:
              name: dbw-dmlz-nsg
            spec:
              resourceGroupName: ""
              dbwPublicSubnetId: ""
              dbwPrivateSubnetId: ""
          patches:
            - type: FromEnvironmentFieldPath
              fromFieldPath: outputs.ResourceGroupName
              toFieldPath: spec.resourceGroupName
            - type: FromCompositeFieldPath
              fromFieldPath: spec.providerConfigName
              toFieldPath: spec.providerConfigName
            - type: FromCompositeFieldPath
              fromFieldPath: spec.location
              toFieldPath: spec.location
            - type: FromCompositeFieldPath
              fromFieldPath: spec.environment
              toFieldPath: spec.environment
            - type: FromCompositeFieldPath
              fromFieldPath: status.outputs.dbwPublicSubnetId
              toFieldPath: spec.dbwPublicSubnetId
            - type: FromCompositeFieldPath
              fromFieldPath: status.outputs.dbwPrivateSubnetId
              toFieldPath: spec.dbwPrivateSubnetId
            - type: ToCompositeFieldPath
              fromFieldPath: status.outputs.privateNsgAssociationId
              toFieldPath: status.outputs.privateNsgAssociationId
            - type: ToCompositeFieldPath
              fromFieldPath: status.outputs.publicNsgAssociationId
              toFieldPath: status.outputs.publicNsgAssociationId


        - name: dbw-dmlz
          base:
            apiVersion: databricks.azure.upbound.io/v1beta1
            kind: Workspace
            metadata:
              labels:
                planum.mblb.net/component: dbw-dmlz
              name: dbw-dmlz
            spec:
              forProvider:
                sku: premium
                publicNetworkAccessEnabled: false
                networkSecurityGroupRulesRequired: "NoAzureDatabricksRules"
                customParameters:
                  - noPublicIp: true
                    publicSubnetNameSelector: 
                      matchLabels:
                        planum.mblb.net/component: snet-dmlz-dbw-public
                    publicSubnetNetworkSecurityGroupAssociationId: ""
                    privateSubnetNameSelector: 
                      matchLabels:
                        planum.mblb.net/component: snet-dmlz-dbw-private
                    privateSubnetNetworkSecurityGroupAssociationId: ""
                    virtualNetworkId:
                    vnetAddressPrefix:
          patches:
            - type: CombineFromComposite
              combine:
                variables:
                  - fromFieldPath: metadata.name
                  - fromFieldPath: spec.environment
                  - fromFieldPath: spec.location
                strategy: string
                string:
                  fmt: "dbw-%s-%s-%s"
              toFieldPath: metadata.name
            - type: FromEnvironmentFieldPath
              fromFieldPath: outputs.ResourceGroupName
              toFieldPath: spec.forProvider.resourceGroupName
            - type: FromEnvironmentFieldPath
              fromFieldPath: outputs.VirtualNetworkId
              toFieldPath: spec.forProvider.customParameters[0].virtualNetworkId
            - type: FromEnvironmentFieldPath
              fromFieldPath: outputs.vnetAddressPrefix
              toFieldPath: spec.forProvider.customParameters[0].vnetAddressPrefix
            - type: FromCompositeFieldPath
              fromFieldPath: status.outputs.publicNsgAssociationId
              toFieldPath: spec.forProvider.customParameters[0].publicSubnetNetworkSecurityGroupAssociationId
            - type: FromCompositeFieldPath
              fromFieldPath: status.outputs.privateNsgAssociationId
              toFieldPath: spec.forProvider.customParameters[0].privateSubnetNetworkSecurityGroupAssociationId
            - type: ToCompositeFieldPath
              fromFieldPath: status.atProvider.id
              toFieldPath: status.outputs.databricksId
            - type: ToCompositeFieldPath
              fromFieldPath: status.atProvider.workspaceUrl
              toFieldPath: status.outputs.dbwUrl
            - type: FromCompositeFieldPath
              fromFieldPath: spec.providerConfigName
              toFieldPath: spec.providerConfigRef.name
            - type: FromCompositeFieldPath
              fromFieldPath: spec.location
              toFieldPath: spec.forProvider.location
              
        - name: pe-dbw-dmlz
          base:
            apiVersion: network.azure.upbound.io/v1beta1
            kind: PrivateEndpoint
            metadata:
              labels:
                planum.mblb.net/component: pe-dbw-dmlz
            spec:
              forProvider:
                privateDnsZoneGroup:
                  - name: pdzg-dbw-dmlz
                    privateDnsZoneIds:
                    - ""
                privateServiceConnection:
                  - isManualConnection: false
                    name: psc-dbw-dmlz
                    privateConnectionResourceId: ""
                    subresourceNames: ["databricks_ui_api"]
                resourceGroupName: ""
                subnetIdSelector:
                  matchLabels:
                    planum.mblb.net/component: snet-dmlz-pe
          patches:
            - type: CombineFromComposite
              combine:
                variables:
                  - fromFieldPath: metadata.name
                  - fromFieldPath: spec.environment
                  - fromFieldPath: spec.location
                strategy: string
                string:
                  fmt: "pe-dbw-%s-%s-%s"
              toFieldPath: metadata.name
            - type: FromEnvironmentFieldPath
              fromFieldPath: outputs.ResourceGroupName
              toFieldPath: spec.forProvider.resourceGroupName
            - type: FromEnvironmentFieldPath
              fromFieldPath: outputs['privatelink.azuredatabricks.net']
              toFieldPath: spec.forProvider.privateDnsZoneGroup[0].privateDnsZoneIds[0]
            - type: FromCompositeFieldPath
              fromFieldPath: status.outputs.databricksId
              toFieldPath: spec.forProvider.privateServiceConnection[0].privateConnectionResourceId
            - type: FromCompositeFieldPath
              fromFieldPath: spec.providerConfigName
              toFieldPath: spec.providerConfigRef.name
            - type: FromCompositeFieldPath
              fromFieldPath: spec.location
              toFieldPath: spec.forProvider.location

        - name: pe-dbw-dmlz-browser-auth
          base:
            apiVersion: network.azure.upbound.io/v1beta1
            kind: PrivateEndpoint
            metadata:
              labels:
                planum.mblb.net/component: pe-dbw-dmlz-browser-auth
            spec:
              forProvider:
                privateDnsZoneGroup:
                  - name: pdzg-dbw-dmlz-browser-auth
                    privateDnsZoneIds:
                    - ""
                privateServiceConnection:
                  - isManualConnection: false
                    name: psc-dbw-dmlz-browser-auth
                    privateConnectionResourceId: ""
                    subresourceNames: ["browser_authentication"]
                resourceGroupName: ""
                subnetIdSelector:
                  matchLabels:
                    planum.mblb.net/component: snet-dmlz-pe
          patches:
            - type: CombineFromComposite
              combine:
                variables:
                  - fromFieldPath: metadata.name
                  - fromFieldPath: spec.environment
                  - fromFieldPath: spec.location
                strategy: string
                string:
                  fmt: "pe-dbw-browser-auth-%s-%s-%s"
              toFieldPath: metadata.name
            - type: FromEnvironmentFieldPath
              fromFieldPath: outputs.ResourceGroupName
              toFieldPath: spec.forProvider.resourceGroupName
            - type: FromEnvironmentFieldPath
              fromFieldPath: outputs['privatelink.azuredatabricks.net']
              toFieldPath: spec.forProvider.privateDnsZoneGroup[0].privateDnsZoneIds[0]
            - type: FromCompositeFieldPath
              fromFieldPath: status.outputs.databricksId
              toFieldPath: spec.forProvider.privateServiceConnection[0].privateConnectionResourceId
            - type: FromCompositeFieldPath
              fromFieldPath: spec.providerConfigName
              toFieldPath: spec.providerConfigRef.name
            - type: FromCompositeFieldPath
              fromFieldPath: spec.location
              toFieldPath: spec.forProvider.location

        - name: rt-association-snet-dmlz-pe
          base:
            apiVersion: network.azure.upbound.io/v1beta1
            kind: SubnetRouteTableAssociation
            metadata:
              name: rt-association-snet-dmlz-pe
            spec:
              forProvider:
                routeTableId: 
                subnetIdSelector:
                  matchControllerRef: true
                  matchLabels:
                    planum.mblb.net/component: snet-dmlz-pe
          patches:
            - type: FromEnvironmentFieldPath
              fromFieldPath: outputs.routeTableId
              toFieldPath: spec.forProvider.routeTableId
            - type: FromCompositeFieldPath
              fromFieldPath: spec.providerConfigName
              toFieldPath: spec.providerConfigRef.name

        - name: rt-association-snet-dmlz-dbw-public
          base:
            apiVersion: network.azure.upbound.io/v1beta1
            kind: SubnetRouteTableAssociation
            metadata:
              name: rt-association-snet-dmlz-dbw-public
            spec:
              forProvider:
                routeTableId: 
                subnetIdSelector:
                  matchControllerRef: true
                  matchLabels:
                    planum.mblb.net/component: snet-dmlz-dbw-public
          patches:
            - type: FromEnvironmentFieldPath
              fromFieldPath: outputs.routeTableId
              toFieldPath: spec.forProvider.routeTableId
            - type: FromCompositeFieldPath
              fromFieldPath: spec.providerConfigName
              toFieldPath: spec.providerConfigRef.name

        - name: rt-association-snet-dmlz-dbw-private
          base:
            apiVersion: network.azure.upbound.io/v1beta1
            kind: SubnetRouteTableAssociation
            metadata:
              name: rt-association-snet-dmlz-dbw-private
            spec:
              forProvider:
                routeTableId: 
                subnetIdSelector:
                  matchControllerRef: true
                  matchLabels:
                    planum.mblb.net/component: snet-dmlz-dbw-private
          patches:
            - type: FromEnvironmentFieldPath
              fromFieldPath: outputs.routeTableId
              toFieldPath: spec.forProvider.routeTableId
            - type: FromCompositeFieldPath
              fromFieldPath: spec.providerConfigName
              toFieldPath: spec.providerConfigRef.name

        - name: rt-association-snet-dmlz-agent
          base:
            apiVersion: network.azure.upbound.io/v1beta1
            kind: SubnetRouteTableAssociation
            metadata:
              name: rt-association-snet-dmlz-agent
            spec:
              forProvider:
                routeTableId: 
                subnetIdSelector:
                  matchControllerRef: true
                  matchLabels:
                    planum.mblb.net/component: snet-dmlz-agent
          patches:
            - type: FromEnvironmentFieldPath
              fromFieldPath: outputs.routeTableId
              toFieldPath: spec.forProvider.routeTableId
            - type: FromCompositeFieldPath
              fromFieldPath: spec.providerConfigName
              toFieldPath: spec.providerConfigRef.name