apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xdmlzs.planum.mblb.net
spec:
  group: planum.mblb.net
  names:
    kind: XDmlz
    plural: xdmlzs

  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              resourceConfig:
                description: ResourceConfig defines general properties
                type: object
                properties:
                  providerConfigName:
                    type: string
                  location:
                    type: string
                  environment:
                    type: string
                  spokeName:
                    type: string
                  tenantId:
                    type: string
                required:
                  - providerConfigName
                  - location
              parameters:
                description: DMLZ Input parameters
                type: object
                properties:
                  resourceGroupName:
                    type: string
                  vnetName:
                    type: string
                  routeTableId: 
                    type: string
                  virtualNetworkId:
                    type: string
                  virtualNetworkPrefix:
                    type: string
                  subnets:
                    type: array
                    default:
                    - name: "snet-dmlz-eventhub"
                      addressPostfix: "64/28"
                    - name: "snet-dmlz-agent"
                      addressPostfix: "80/29"
                    - name: "snet-dmlz-pe"
                      addressPostfix: "96/27"
                    - name: "snet-dmlz-dbw-public"
                      addressPostfix: "128/26"
                    - name: "snet-dmlz-dbw-private"
                      addressPostfix: "192/26"
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        addressPostfix:
                          type: string
                  databricksConfig:
                    type: object
                    properties:
                      privateDnsZoneId:
                        type: string
          status:
            type: object
            properties:
              outputs:
                type: object
                additionalProperties:
                  type: string