apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xlakehouses.planum.mblb.net
spec:
  group: planum.mblb.net
  names:
    kind: XLakehouse
    plural: xlakehouses

  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              resourceConfig:
                description: ResourceConfig defines general properties
                type: object
                properties:
                  providerConfigName:
                    type: string
                  location:
                    type: string
                  environment:
                    type: string
                  tenantId:
                    type: string 
                required:
                  - providerConfigName
                  - location
              parameters:
                description: DMLZ Input parameters
                type: object
                properties:
                  xNetworkName:
                    type: string
                  xDnsName:
                    type: string
                  virtualNetworkPrefix:
                    type: string
                  subnets:
                    type: array
                    default:
                    - name: "snet-cp-spoke-eus-agent"
                      addressPostfix: "64/29"
                    - name: "snet-cp-spoke-eus-pe"
                      addressPostfix: "0/26"
                    - name: "snet-cp-spoke-eus-dbw-public"
                      addressPostfix: "128/26"
                    - name: "snet-cp-spoke-eus-dbw-private"
                      addressPostfix: "192/26"
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        addressPostfix:
                          type: string

                  keyvault:
                    type: object
                    properties:
                      accessPolicies:
                        type: array
                        items:
                          type: object
                          properties:
                            objectId:
                              type: string
                            certificatePermissions:
                              items:
                                type: string
                              type: array
                            keyPermissions:
                              items:
                                type: string
                              type: array
                            secretPermissions:
                              items:
                                type: string
                              type: array
          status:
            type: object
            properties:
              outputs:
                type: object
                additionalProperties:
                  type: string