apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xlakehouses.planum.mblb.net
spec:
  group: planum.mblb.net
  names:
    kind: XLakehouse
    plural: xlakehouses

  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              providerConfigName:
                type: string
              location:
                type: string
              environment:
                type: string
              xNetworkName:
                type: string
              xDnsName:
                type: string
              keyvault:
                type: object
                properties:
                  accessPolicies:
                    type: array
                    items:
                      type: object
                      properties:
                        objectId:
                          type: string
                        certificatePermissions:
                          items:
                            type: string
                          type: array
                        keyPermissions:
                          items:
                            type: string
                          type: array
                        secretPermissions:
                          items:
                            type: string
                          type: array

            required:
              - providerConfigName
              - location
              - xNetworkName
              - xDnsName

          status:
            type: object
            properties:
              outputs:
                type: object
                additionalProperties:
                  type: string