apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: planum-project
spec:
  dependsOn:
  - provider: xpkg.upbound.io/upbound/provider-azure-authorization
    version: ">=v1.0.1"
  - provider: xpkg.upbound.io/upbound/provider-azure-compute
    version: ">=v1.0.1"
  - provider: xpkg.upbound.io/upbound/provider-azure-containerservice
    version: ">=v1.0.1"
  - provider: xpkg.upbound.io/upbound/provider-azure-databricks
    version: ">=v1.0.1"
  - provider: xpkg.upbound.io/upbound/provider-azure-datafactory
    version: ">=v1.0.1"
  - provider: xpkg.upbound.io/upbound/provider-azure-managedidentity
    version: ">=v1.0.1"
  - provider: xpkg.upbound.io/upbound/provider-azure-operationalinsights
    version: ">=v1.0.1"
  - provider: xpkg.upbound.io/upbound/provider-azure-storage
    version: ">=v1.0.1"
  - provider: mobilab.azurecr.io/provider-databricks-crossplane
    version: ">=v0.3.1"
  - provider: xpkg.upbound.io/crossplane-contrib/provider-nop
    version: ">=v0.2.1"
  - provider: mobilab.azurecr.io/provider-azuread
    version: "v0.1.7"
  - provider: mobilab.azurecr.io/provider-github
    version: "v0.1.10"
  - function: xpkg.upbound.io/crossplane-contrib/function-go-templating 
    version: ">=v0.4.1"
  - function: xpkg.upbound.io/crossplane-contrib/function-auto-ready
    version: ">=v0.2.1"
  - function: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform
    version: ">=v0.4.0"
  - function: xpkg.upbound.io/crossplane-contrib/function-cel-filter
    version: ">=v0.1.1"
  crossplane:
    version: ">=v1.14.4"
