apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xunitycatalogs.planum.mblb.net
spec:
  group: planum.mblb.net
  names:
    kind: XUnityCatalog
    plural: xunitycatalogs

  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              resourceConfig:
                description: ResourceConfig defines general properties
                type: object
                properties:
                  providerConfigName:
                    type: string
                  location:
                    type: string
                  environment:
                    type: string
                required:
                  - providerConfigName
                  - location

              parameters:
                description: Unity Catalog Input parameters
                type: object
                properties:
                  xLakehouseName:
                    type: string
                  metastoreId:
                    type: string
                  clusters:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        sparkVersion:
                          type: string
                        nodeTypeId:
                          type: string
                        runtimeEngine:
                          type: string
                        numWorkers:
                          type: integer
                          minimum: 0
                        jar:
                          type: string
                        maven:
                          items:
                            properties:
                              coordinates:
                                type: string
                              exclusions:
                                items:
                                  type: string
                                type: array
                              repo:
                                type: string
                            type: object
                          type: array
                        pypi:
                          items:
                            properties:
                              package:
                                type: string
                              repo:
                                type: string
                            type: object
                          type: array
                        whl:
                          type: string
                  catalogs:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        owner:
                          type: string
                        storageRoot:
                          type: string
                        properties:
                          type: string
                        grants:
                          type: array
                          items:
                            type: object
                            properties:
                              principal:
                                type: string
                              privileges:
                                type: array
                                items:
                                  type: string

                  locations:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        owner:
                          type: string
                        url:
                          type: string
                        grants:
                          type: array
                          items:
                            type: object
                            properties:
                              principal:
                                type: string
                              privileges:
                                type: array
                                items:
                                  type: string
                        schemas:
                          type: array
                          items:
                            type: object
                            properties:
                              name:
                                type: string
                              grants:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    principal:
                                      type: string
                                    privileges:
                                      type: array
                                      items:
                                        type: string

          status:
            type: object
            properties:
              outputs:
                type: object
                additionalProperties:
                  type: string