apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xunitycatalogs.planum.mblb.net
spec:
  group: planum.mblb.net
  names:
    kind: XUnityCatalog
    plural: xunitycatalogs

  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              resourceConfig:
                description: ResourceConfig defines general properties
                type: object
                properties:
                  providerConfigName:
                    type: string
                  location:
                    type: string
                  environment:
                    type: string
                required:
                  - providerConfigName
                  - location

              parameters:
                description: Unity Catalog Input parameters
                type: object
                properties:
                  metastoreId:
                    type: string
                  storageAccountName:
                    type: string

          status:
            type: object
            properties:
              outputs:
                type: object
                additionalProperties:
                  type: string