name: Planum - Push configuration package

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'Enter the Package version'
        default: 'latest'

permissions:
  id-token: write
  contents: read
      
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:          
      - uses: actions/checkout@v3

      - name: Azure login
        uses: Azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Pushing packages to planum registry
        run: |
          az acr login -n ${{ vars.CONTAINER_REGISTRY }}
          XP_VERSION=v1.15.0
          curl -sL "https://raw.githubusercontent.com/crossplane/crossplane/master/install.sh" | XP_VERSION=$XP_VERSION sh
          ./crossplane xpkg build --package-root="crossplane/hubandspoke/" --package-file=planum-project.xpkg 
          ./crossplane xpkg push -f planum-project.xpkg ${{ vars.CONTAINER_REGISTRY }}/planum-project:${{ inputs.version }}