apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xdbwnsg.planum.mblb.net
spec:
  group: planum.mblb.net
  names:
    kind: XDbwNsg
    plural: xdbwnsg

  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              providerConfigName:
                type: string
              location:
                type: string
              environment:
                type: string
              resourceGroupName:
                type: string
              dbwPublicSubnetId:
                type: string
              dbwPrivateSubnetId:
                type: string
            required:
              - providerConfigName
              - location
              - environment

          status:
            type: object
            properties:
              outputs:
                type: object
                additionalProperties:
                  type: string